### ISSUE TITLE
Latest version of CLI (3.128.0) didn't make it to Winget

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-winget#29]
### What happened?

https://github.com/pulumi/pulumi-winget/actions/runs/10254887812

### Example

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The problem is the first run of the workflow failed to publish to winget:

https://github.com/pulumi/pulumi-winget/actions/runs/10254887812/job/28370618279#step:7:18

```
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle
```

Re-running the workflow succeeded, but since the .msi was already published to GitHub in a GitHub release, the publish to winget was skipped.

https://github.com/pulumi/pulumi-winget/blob/70e7b1c0f2e114954fb6b1305a186592169d15b8/src/Program.fs#L207-L209

https://github.com/pulumi/pulumi-winget/blob/70e7b1c0f2e114954fb6b1305a186592169d15b8/.github/workflows/generate-msi.yml#L34-L38

We should update the workflow so that even if the release already exists on GitHub, it will still try to publish to winget.

**Comment by Zaid-Ajaj** [comment]
@justinvp if a release exists on Github, you can just delete and re-run the workflow

**Comment by justinvp** [comment]
> if a release exists on Github, you can just delete and re-run the workflow

Good point. I went ahead and did that. The PR is now open to add the version to winget: https://github.com/microsoft/winget-pkgs/pull/167028
